[project]
name = "robot-udemy"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "pyserial>=3.5",
    "pytest>=9.0.2",
    "smbus2",
    "spidev",
    "robotframework==7.4.1",
    "robotframework-seleniumlibrary==6.8.0",
]
